### ISSUE TITLE
Unable to update current badge using a release train

### ISSUE THREAD

**Issue by spencergibb** [spring-io/sagan#800] opened 2017-11-27 20:56 UTC
http://projects.spring.io/spring-cloud/

To get the current badge to work for recently released Edgware.RELEASE, I had to delete everything lexically below Edgware, then set the current badge, then add everything back. I'm unable to update the current badge. This has been an issue for a while.

**Comment by bclozel** [comment] 2020-05-29 08:28
Duplicate of #903

**Closed by bclozel** 2020-05-29 08:28 UTC
