### ISSUE TITLE
Build failed at "Run the site locally" Section

### ISSUE THREAD

**Issue by Excelnd** [spring-io/sagan#1016] opened 2021-01-19 16:23 UTC
[Build Failed.txt](https://github.com/spring-io/sagan/files/5837206/Build.Failed.txt)
Execution failed for task ':sagan-client:npm_run_build'.

Please check the text file.

**Comment by bclozel** [comment] 2021-01-19 16:27
Closing as a duplicate of #979

**Closed by bclozel** 2021-01-19 16:27 UTC
