### ISSUE TITLE
Cloud Foundry: Sagan app failed (crashed) when starting

### ISSUE THREAD

**Issue by tatefer** [spring-io/sagan#605] opened 2015-11-25 14:52 UTC
Hi.

After the "cf push sagan -n tatefer-sagan -p build/libs/sagan-site.jar" command, the sagan application is unable to start succesfully.
I have stored the logs (attached) and first line with an error is:

-------------------------------------------------
2015-11-25T06:13:59.06-0800 [APP/0]      OUT 2015-11-25 14:13:59.067 ERROR 26 --- [ost-startStop-1] o.s.b.c.embedded.tomcat.TomcatStarter    : Error starting Tomcat context: org.springframework.beans.factory.UnsatisfiedDependencyException
2015-11-25T06:13:59.13-0800 [APP/0]      OUT 2015-11-25 14:13:59.136  WARN 26 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt
2015-11-25T06:13:59.13-0800 [APP/0]      OUT org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.boot.context.embedded.EmbeddedServletContainerException: Unable to start embedded Tomcat

-------------------------------------------------

Everything before the execution of "cf push" command was ok (gradlew, etc...) and I can see the app in my Pivotal Web Services Dashboard. 

[logs.txt](https://github.com/spring-io/sagan/files/43962/logs.txt)
Please, find attached log file for the "cf push" output command.
Can anyone help me?

Best Regards and thanks in advance.

**Comment by bclozel** [comment] 2015-11-25 20:46
Hi @tatefer 
This is indeed a bug in Sagan; when deploying an application in PWS, the "cloud" Spring profile is automatically registered. This prevents the "default" profile from being activated, which means the `SaganProfiles.STANDALONE` profile is not triggered when the application starts.
In your case, the logs say that a Spring bean is missing (here, `JestClient`) although it's required by the application.

I've fixed this in #607 - could you update your git repository and try again?
Don't hesitate to ask questions by creating new issues - even if those are general questions about choice of architecture, etc.

I'll close this issue once you've confirmed it's OK.

Thanks,

**Comment by tatefer** [comment] 2015-11-26 09:38
Brian,  many thanks for your support.
I will follow your recommendations and will let you know.

Regards.

**Comment by tatefer** [comment] 2015-11-27 12:00
Hi Brian.
Many thanks, it worked!!
I downloaded the updated repository and everything was ok.
After deploying the sagan app with "cf push", the app started and is running succesfully.

0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
0 of 1 instances running, 1 starting
1 of 1 instances running

App started


OK

App sagan was started using this command `CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-2.0.1_RELEASE -memorySizes=metaspace:64m.. -memoryWeights=heap:75,metaspace:10,native:10,stack:5 -memoryInitials=heap:100%,metaspace:100% -totMemory=$MEMORY_LIMIT) && SERVER_PORT=$PORT $PWD/.java-buildpack/open_jdk_jre/bin/java -cp $PWD/.:$PWD/.java-buildpack/spring_auto_reconfiguration/spring_auto_reconfiguration-1.10.0_RELEASE.jar -Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh $CALCULATED_MEMORY org.springframework.boot.loader.JarLauncher`

Showing health and status for app sagan in org TateOrg / space TateSpace as fernando.cuevas@emc.com...
OK

requested state: started
instances: 1/1
usage: 1G x 1 instances
urls: xxxxxx-sagan.cfapps.io
last uploaded: Fri Nov 27 11:54:40 UTC 2015
stack: cflinuxfs2
buildpack: java-buildpack=v3.3.1-https://github.com/cloudfoundry/java-buildpack.git#063836b java-main open-jdk-like-jre=1.8.0_65 open-jdk-like-memory-calculator=2.0.1_RELEASE spring-auto-reconfiguration=1.10.0_RELEASE

     state     since                    cpu      memory         disk           details   
#0   running   2015-11-27 12:56:22 PM   227.0%   660.9M of 1G   248.2M of 1G

**Comment by tatefer** [comment] 2015-11-27 12:23
Hi Brian.

I was happy until I had to bind the app to the postgres SQL service.
I used the command "cf bind-service sagan sagan-db" and afterwards I did a "cf restage sagan".

The restage of the app failed, and same error occured than above messages.

The app failed to start. Find attached the "cf logs --recent" output

[logs_sagan_restage.txt](https://github.com/spring-io/sagan/files/45699/logs_sagan_restage.txt)

**Comment by bclozel** [comment] 2015-11-27 13:05
I think you forgot to `set-env` a profile for your application.
When running the application in standalone mode, it's "self-contained" with an in-memory database and cache. Since you want now to bind to services and persist data to a shared datastore, use a distributed cache (and maybe run multiple instances?), you need to activate a `staging` or `production` profile. Note that this isn't enforced by CloudFoundry nor Spring Boot, but rather a convention defined in [Sagan's source code](https://github.com/spring-io/sagan/blob/master/sagan-common/src/main/java/sagan/SaganProfiles.java).

For more details on the steps to follow, [check out the wiki documentation](https://github.com/spring-io/sagan/wiki/Configure-Marketplace-services).

**Comment by tatefer** [comment] 2015-11-27 15:47
Many thaks Brian, you were right.
I did the "cf restage" before set-env a profile.
But despite of set-env the profile to staging, the app doesn't start succesfully.

See logs file attached. I don't know what I'm doing wrong :-(

[logs_restage_after_set_env.txt](https://github.com/spring-io/sagan/files/45893/logs_restage_after_set_env.txt)

tatefer@ubuntu:~/CloudFoundry/sagan$ cf env sagan
Getting env variables for app sagan in org TateOrg / space TateSpace as fernando.cuevas@emc.com...
OK

System-Provided:
{
 "VCAP_SERVICES": {
  "elephantsql": [
   {
    "credentials": {
     "max_conns": "5",
     "uri": "postgres://zkdpfilp:_je62Aa2SiKupulzzL_haRJ_BQxNyTWj@pellefant-01.db.elephantsql.com:5432/zkdpfilp"
    },
    "label": "elephantsql",
    "name": "sagan-db",
    "plan": "turtle",
    "tags": [
     "Data Stores",
     "Web-based",
     "User Provisioning",
     "PaaS",
     "Single Sign-On",
     "Windows",
     "New Product",
     "Mac",
     "Android",
     "Certified Applications",
     "Data Store",
     "postgresql",
     "Buyable",
     "relational",
     "Importable",
     "IT Management"
    ]
   }
  ]
 }
}

{
 "VCAP_APPLICATION": {
  "application_id": "804e9389-b321-4c56-867d-baf2cafb9fd3",
  "application_name": "sagan",
  "application_uris": [
   "tatefer-sagan.cfapps.io"
  ],
  "application_version": "7a1487e0-2843-4913-8d78-e49c7bc9e6bf",
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 1024
  },
  "name": "sagan",
  "space_id": "c8ee9dc5-c03b-4eeb-baa6-ffade04fe41e",
  "space_name": "TateSpace",
  "uris": [
   "tatefer-sagan.cfapps.io"
  ],
  "users": null,
  "version": "7a1487e0-2843-4913-8d78-e49c7bc9e6bf"
 }
}

User-Provided:
SPRING_PROFILES_ACTIVE: staging

No running env variables have been set

No staging env variables have been set

Regards.

**Comment by bclozel** [comment] 2015-11-27 15:54
Ah, I think you need to set up the ElasticSearch service as well.
```
Caused by: java.lang.IllegalArgumentException: ElasticSearch endpoint URI should not be null: cloud.services.sagan-search.connection.uri
```

This may be a requirement I can relax a bit. See [that part of the wiki](https://github.com/spring-io/sagan/wiki/Enable-search-on-Cloud-Foundry).

**Comment by tatefer** [comment] 2015-11-27 22:37
Thanks once again Brian!!
Very appreciated!!. The app is right now started and running!!
Sorry for any inconvenience and many thanks again for your help.

**Closed** 2015-11-30 16:26 UTC
Labels: a: question, in progress
