### ISSUE TITLE
when execute "gradlew :sagan-site:bootrun", get an exception: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal

### ISSUE THREAD

**Issue by SumanthBala** [spring-io/sagan#840] opened 2018-06-06 12:08 UTC
**when execute "gradlew :sagan-site:bootrun", get an exception: java.lang.ClassNotFoundException: org.w3c.dom.ElementTraversal,**
-tried of many times but getting the same error , replicated in multiple systems****

**Comment by bclozel** [comment] 2018-06-18 17:17
I can't reproduce this - could you tell me a bit more so I can try to figure this out?
What's your Java version, operating system? The ouput of `./gradlew --version` should help.

**Comment by bclozel** [comment] 2020-04-07 17:10
Closing since we couldn't reproduce this and didn't get feedback.

**Closed by bclozel** 2020-04-07 17:10 UTC
