### ISSUE TITLE
Unable to mark spring-cloud Dalston.RELEASE as current

### ISSUE THREAD

**Issue by spencergibb** [spring-io/sagan#715] opened 2017-04-14 20:26 UTC
https://spring.io/admin/projects/spring-cloud

There are no errors in the JS Console.

**Comment by jkschneider** [comment] 2017-04-14 20:27
You also cannot change the reference link.

However, if you first rename `Dalston.RELEASE` to `Dalston.SR1`, you can both change the reference link and mark it current.

**Comment by bclozel** [comment] 2017-04-14 21:12
data looks good now - is this because of the workaround you've found?

**Comment by jkschneider** [comment] 2017-04-14 21:15
Yep, deleting the entry and re-adding it with the current checkbox checked works around it

**Comment by jkschneider** [comment] 2017-04-14 21:16
It's a front end problem somehow, the `current` check value is not correctly sent to the backend.

**Comment by jkschneider** [comment] 2017-04-14 21:16
Also, releases are sorted by SR# rather than release train name.

**Comment by bclozel** [comment] 2020-05-29 08:29
Duplicate of #903

**Closed by bclozel** 2020-05-29 08:29 UTC
