### ISSUE TITLE
:sagan-site:generateGitProperties FAILED

### ISSUE THREAD

**Issue by zminor** [spring-io/sagan#731] opened 2017-07-15 12:22 UTC
I used git clone https://github.com/git/git  , the problem is still there , help please?

D:\Programming\Java\Eclipse workspace\sagan-master\sagan-master>gradle generateGitProperties --info
Starting Build
Settings evaluated using settings file 'D:\Programming\Java\Eclipse workspace\sagan-master\sagan-master\settings.gradle'.
Projects loaded. Root project using build file 'D:\Programming\Java\Eclipse workspace\sagan-master\sagan-master\build.gradle'.
Included projects: [root project 'sagan', project ':sagan-client', project ':sagan-common', project ':sagan-indexer', project ':sagan-site']
Evaluating root project 'sagan' using build file 'D:\Programming\Java\Eclipse workspace\sagan-master\sagan-master\build.gradle'.
Applying dependency management to configuration 'archives' in project 'sagan-site'
Applying dependency management to configuration 'compile' in project 'sagan-site'
Applying dependency management to configuration 'compileClasspath' in project 'sagan-site'
Applying dependency management to configuration 'compileOnly' in project 'sagan-site'
Applying dependency management to configuration 'default' in project 'sagan-site'
Applying dependency management to configuration 'runtime' in project 'sagan-site'
Applying dependency management to configuration 'testCompile' in project 'sagan-site'
Applying dependency management to configuration 'testCompileClasspath' in project 'sagan-site'
Applying dependency management to configuration 'testCompileOnly' in project 'sagan-site'
Applying dependency management to configuration 'testRuntime' in project 'sagan-site'
Applying dependency management to configuration 'archives' in project 'sagan-indexer'
Applying dependency management to configuration 'compile' in project 'sagan-indexer'
Applying dependency management to configuration 'compileClasspath' in project 'sagan-indexer'
Applying dependency management to configuration 'compileOnly' in project 'sagan-indexer'
Applying dependency management to configuration 'default' in project 'sagan-indexer'
Applying dependency management to configuration 'runtime' in project 'sagan-indexer'
Applying dependency management to configuration 'testCompile' in project 'sagan-indexer'
Applying dependency management to configuration 'testCompileClasspath' in project 'sagan-indexer'
Applying dependency management to configuration 'testCompileOnly' in project 'sagan-indexer'
Applying dependency management to configuration 'testRuntime' in project 'sagan-indexer'
Applying dependency management to configuration 'archives' in project 'sagan-common'
Applying dependency management to configuration 'compile' in project 'sagan-common'
Applying dependency management to configuration 'compileClasspath' in project 'sagan-common'
Applying dependency management to configuration 'compileOnly' in project 'sagan-common'
Applying dependency management to configuration 'default' in project 'sagan-common'
Applying dependency management to configuration 'runtime' in project 'sagan-common'
Applying dependency management to configuration 'testCompile' in project 'sagan-common'
Applying dependency management to configuration 'testCompileClasspath' in project 'sagan-common'
Applying dependency management to configuration 'testCompileOnly' in project 'sagan-common'
Applying dependency management to configuration 'testRuntime' in project 'sagan-common'
Applying dependency management to configuration 'integTestCompile' in project 'sagan-site'
Applying dependency management to configuration 'integTestRuntime' in project 'sagan-site'
Applying dependency management to configuration 'integTestCompileOnly' in project 'sagan-site'
Applying dependency management to configuration 'integTestCompileClasspath' in project 'sagan-site'
Applying dependency management to configuration 'integTestCompile' in project 'sagan-indexer'
Applying dependency management to configuration 'integTestRuntime' in project 'sagan-indexer'
Applying dependency management to configuration 'integTestCompileOnly' in project 'sagan-indexer'
Applying dependency management to configuration 'integTestCompileClasspath' in project 'sagan-indexer'
Evaluating project ':sagan-client' using build file 'D:\Programming\Java\Eclipse workspace\sagan-master\sagan-master\sagan-client\build.gradle'.
Evaluating project ':sagan-common' using build file 'D:\Programming\Java\Eclipse workspace\sagan-master\sagan-master\sagan-common\build.gradle'.
Applying dependency management to configuration 'testUtilCompile' in project 'sagan-common'
Applying dependency management to configuration 'testUtilRuntime' in project 'sagan-common'
Applying dependency management to configuration 'testUtilCompileOnly' in project 'sagan-common'
Applying dependency management to configuration 'testUtilCompileClasspath' in project 'sagan-common'
Evaluating project ':sagan-indexer' using build file 'D:\Programming\Java\Eclipse workspace\sagan-master\sagan-master\sagan-indexer\build.gradle'.
Configuring agent
Evaluating project ':sagan-site' using build file 'D:\Programming\Java\Eclipse workspace\sagan-master\sagan-master\sagan-site\build.gradle'.
Applying dependency management to configuration 'asciidoctor' in project 'sagan-site'
[Asciidoctor] asciidoctorj: 1.5.3.2
[Asciidoctor] asciidoctorj-groovy-dsl: 1.0.0.preview2
Configuring agent
All projects evaluated.
Selected primary task 'generateGitProperties' from project :
Tasks to be executed: [task ':sagan-site:generateGitProperties']
:sagan-site:generateGitProperties (Thread[main,5,main]) started.
:sagan-site:generateGitProperties
Executing task ':sagan-site:generateGitProperties' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:sagan-site:generateGitProperties FAILED
:sagan-site:generateGitProperties (Thread[main,5,main]) completed. Took 0.218 secs.

**Comment by bclozel** [comment] 2020-04-07 17:00
We couldn't reproduce the issue and we've significantly changed the build since. I'm closing this issue now.

**Closed by bclozel** 2020-04-07 17:00 UTC
