### ISSUE TITLE
Fail to do "npm build"

### ISSUE THREAD

**Issue by pasonzhang** [spring-io/sagan#856] opened 2018-09-07 09:04 UTC
following is my problem, can you help me? I have read issues carefully here, and try them,but no answer.

git clone master of sagan project, chmod 777 for the directory. 

environment:
mac os
nvm install 0.12.4  ( I try several node version, 4.4.2 \ 8.x.x, problems are same)
npm -v 2.10.1

firstly, npm install ,  that is ok.
then , npm run build, fail like this:

npm ERR! Darwin 17.6.0
npm ERR! argv "/Users/sunling/.nvm/versions/node/v0.12.4/bin/node" "/Users/sunling/.nvm/versions/node/v0.12.4/bin/npm" "run" "build"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! sagan@ build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sagan@ build script 'gulp build'.
npm ERR! This is most likely a problem with the sagan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sagan
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/iot/spring/sagan/sagan-client/npm-debug.log
[npm-debug.log](https://github.com/spring-io/sagan/files/2360364/npm-debug.log)

**Comment by bclozel** [comment] 2018-09-07 09:11
does it work with `./gradlew :sagan-client:build` ?

**Comment by pasonzhang** [comment] 2018-09-07 13:11
it doesn't work.
nom-debu.log seem same when using ./gradlew :sagan-client:build

**Comment by delvin76** [comment] 2019-12-16 10:37
I also encountered this issue in the windows platform. I resolved this issue in my local box.  Below is the detail. 
Change args = ['run', 'build'] =>  args = ['run, build'] in the below task in sagan\sagan-client\build.gradle file.
task npmBuild(dependsOn: npmInstall, type: NpmTask) {
    inputs.file 'gulpfile.js'
    inputs.dir('src')
    outputs.dir jsBuildDir
    args = ['run', 'build']
}

**Comment by dsyer** [comment] 2019-12-16 11:11
It worked for me on Windows (with WSL). I'm not sure that change you suggest is correct (wouldn't it run a command "run, build" with a comma in it?).

**Comment by delvin76** [comment] 2019-12-17 10:49
Today I checked it again. It seems the suggestion is not correct. It works becaue I change the args=['run'] and run gradlew.bat :sagan-site:bootRun, then I changed args=['run, build'], run gradlew.bat :sagan-site:bootRun again. I didn't run clean after i changed args =['run, build']. So the second bootRun didn't need to run npmBuild task.

**Comment by bclozel** [comment] 2020-04-07 17:05
I've upgraded Gradle and changed the Node.js Gradle plugin, as well as rewrote the complete client build. I can't reproduce so I'm closing this issue for now.

**Closed by bclozel** 2020-04-07 17:05 UTC
