### ISSUE TITLE
Can't build master

### ISSUE THREAD

**Issue by smcgow** [spring-io/sagan#1030] opened 2021-04-28 16:56 UTC
Hi,

I can't build the master code. Getting the following error after a gradle build through command line and intellij environment

ERROR in ./src/css/main.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleParseError: Module parse failed: Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
    at handleParseError (C:\projects\sagan-master\sagan-client\node_modules\webpack\lib\NormalModule.js:469:19)
    at C:\projects\sagan-master\sagan-client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\projects\sagan-master\sagan-client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\projects\sagan-master\sagan-client\node_modules\loader-runner\lib\LoaderRunner.js:373:3

**Comment by bclozel** [comment] 2021-04-28 17:01
Duplicate of #979

**Closed by bclozel** 2021-04-28 17:01 UTC

**Comment by smcgow** [comment] 2021-04-28 17:08
Thanks, collinzuo fix worked, now passed client build.
